

spring:
  datasource:
    name: wblog
    url: jdbc:mysql://localhost:3306/wblog?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
    username: root
    password: zhuzhu

mybatis:
  config-location: classpath:/mybatis-config.xml

#server:
#  port: 8082

logging:
  level:
    org:
    springframework:
    security: info
